[package]
name = "pixelpwnr"
version = "0.1.0"
authors = ["Tim Visée <timvisee@gmail.com>"]

[dependencies]
bufstream = "0.1"
clap = "2.31"
image = "0.22"
num_cpus = "1.8"
regex = "1.3"

[profile.release]
lto = true
